//! Execution: evaluate a tool call against a compiled ruleset.

mod context;
mod pipeline;

pub use context::ExecutionContext;

use crate::compile::RuleAction;
use crate::taxonomy::TaxonomyMapping;

/// Result of evaluating all rules against a tool call.
/// Contains everything needed for audit, analysis, and dashboard display.
#[derive(Debug, Clone)]
pub struct EvalResult {
    // ── Detection ────────────────────────────────────────────
    /// Individual rule matches with full metadata.
    pub rule_matches: Vec<RuleMatch>,
    /// Final combined risk score: max across all layers.
    pub assessed_risk: f64,
    /// Final action (Block > Flag > Pass).
    pub action: RuleAction,
    /// Whether any matched rule is non-exemptable.
    pub has_non_exemptable_block: bool,

    // ── Layer Results (for analysis/audit) ────────────────────
    /// L0: Encoding depth detected by the decode funnel.
    pub decode_depth: u8,
    /// L0: Encodings peeled by the funnel (e.g., ["base64", "gzip"]).
    pub decode_encodings: Vec<String>,
    /// L0: Depth-based risk score contribution.
    pub decode_depth_score: f64,
    /// L2: Aho-Corasick dictionary max risk.
    pub dict_risk: f64,
    /// L2: Number of dictionary keywords matched.
    pub dict_matched_count: usize,
    /// L3: Compound signal score.
    pub signal_risk: f64,
    /// L3: Number of signals that fired.
    pub signal_count: usize,
    /// L3: Names of matched signals.
    pub matched_signals: Vec<String>,

    // ── Text Forms (for debugging) ───────────────────────────
    /// The extracted text that was actually evaluated (JSON values joined).
    pub extracted_text: String,
    /// Number of normalized variants generated by L4.
    pub normalization_variant_count: usize,
}

/// A single rule match from evaluation.
#[derive(Debug, Clone)]
pub struct RuleMatch {
    pub rule_id: String,
    pub risk_score: f64,
    pub action: RuleAction,
    pub priority: u8,
    pub labels: Vec<String>,
    pub reasoning: String,
    pub exemptable: bool,
    /// MITRE ATLAS + OWASP LLM + regulation taxonomy for this rule.
    pub taxonomy: TaxonomyMapping,
}
